var id=0;
export var productsDetails=[
{
    p_id:++id,
    p_img:'https://www.reliancedigital.in/wp-content/uploads/2022/03/cover_new_mobiles.jpg',
    p_name:"Mobiles"
},
{
    p_id:++id,
    p_img:'https://i.rtings.com/assets/pages/IxCXzynA/apple-laptop-lineup-20220825-3-medium.jpg',
    p_name:"Laptops"
},
{
    p_id:++id,
    p_img:'https://history-computer.com/wp-content/uploads/2022/06/TV-vs-monitor.jpg',
    p_name:"Televisions"
},
{
    p_id:++id,
    p_img:'https://cdn.thewirecutter.com/wp-content/media/2022/12/androidwatches-2048px-watch5.jpg',
    p_name:"SmartWatches"
},
{
    p_id:++id,
    p_img:'https://static.toiimg.com/thumb/msid-89816672,width-400,resizemode-4/89816672.jpg',
    p_name:"Bluetooths"
},
{
    p_id:++id,
    p_img:'https://media.istockphoto.com/id/1198444825/photo/charging-of-smart-phone-from-power-bank.jpg?s=612x612&w=0&k=20&c=sqmFz3k_GHfNhoSbpP0ko9Csh1Z5C_HcLAUAWCk9_gU=',
    p_name:"PowerBanks"
}
]